services:
  - type: web
    name: smart-tags-predictor
    env: python
    region: frankfurt
    plan: free
    # We enter the directory before running commands
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
