services:
  - type: web
    name: smart-tags-predictor
    env: python
    region: ohio
    plan: free
    
    # This command will list all files so we can see the structure in the logs
    buildCommand: ls -R && pip install -r requirements.txt
    
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
